// Code generated by tools/extract-base-rules.py. DO NOT EDIT.

package pushrules

// This is a port of Synapse's built-in push ruleset,
// rust/src/push/base_rules.rs, at v1.159.0-18-g3db77e80a5. It is extracted
// mechanically rather than typed out: the conditions serialise through serde,
// and a hand transcription of forty rules would be a long list of silent
// opportunities to be subtly wrong.
//
// The five groups and their order are load-bearing. A client evaluates rules in
// the order given, so moving one changes which notification a user gets.
// PushRules::iter interleaves them with the user's own rules as
//
//	prepend override | user override | append override | user content |
//	append content | append postcontent | user room | user sender |
//	user underride | append underride
//
// After a Synapse upgrade, re-run the extractor rather than patching by hand,
// and let cmd/syncdiff confirm the result. A wrong rule here is invisible until
// somebody stops being notified.

// Rule is one push rule. Conditions and actions stay as raw JSON: they are
// passed straight through to the client and never inspected here, because this
// worker reports push rules and does not evaluate them.
type Rule struct {
	RuleID         string
	PriorityClass  int
	Conditions     []string
	Actions        []string
	DefaultEnabled bool

	ruleFlags
}

// basePrependOverride ports BASE_PREPEND_OVERRIDE_RULES.
var basePrependOverride = []Rule{
	{
		RuleID:         "global/override/.m.rule.master",
		PriorityClass:  5,
		DefaultEnabled: false,
	},
}

// baseAppendOverride ports BASE_APPEND_OVERRIDE_RULES.
var baseAppendOverride = []Rule{
	{
		RuleID:        "global/override/.org.matrix.msc4028.encrypted_event",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.room.encrypted\"}",
		},
		Actions: []string{
			"\"notify\"",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.m.rule.suppress_notices",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"content.msgtype\",\"pattern\":\"m.notice\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.m.rule.invite_for_me",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.room.member\"}",
			"{\"kind\":\"event_match\",\"key\":\"content.membership\",\"pattern\":\"invite\"}",
			"{\"kind\":\"event_match\",\"key\":\"state_key\",\"pattern_type\":\"user_id\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.m.rule.member_event",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.room.member\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.im.nheko.msc3664.reply",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"im.nheko.msc3664.related_event_match\",\"key\":\"sender\",\"pattern_type\":\"user_id\",\"rel_type\":\"m.in_reply_to\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\"}",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.m.rule.is_user_mention",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"event_property_contains\",\"key\":\"content.m\\\\.mentions.user_ids\",\"value_type\":\"user_id\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\"}",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.m.rule.contains_display_name",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"contains_display_name\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\"}",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.m.rule.is_room_mention",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"event_property_is\",\"key\":\"content.m\\\\.mentions.room\",\"value\":true}",
			"{\"kind\":\"sender_notification_permission\",\"key\":\"room\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.m.rule.roomnotif",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"sender_notification_permission\",\"key\":\"room\"}",
			"{\"kind\":\"event_match\",\"key\":\"content.body\",\"pattern\":\"@room\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.m.rule.tombstone",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.room.tombstone\"}",
			"{\"kind\":\"event_match\",\"key\":\"state_key\",\"pattern\":\"\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.m.rule.reaction",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.reaction\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.m.rule.room.server_acl",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.room.server_acl\"}",
			"{\"kind\":\"event_match\",\"key\":\"state_key\",\"pattern\":\"\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.m.rule.suppress_edits",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"event_property_is\",\"key\":\"content.m\\\\.relates_to.rel_type\",\"value\":\"m.replace\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/override/.org.matrix.msc3930.rule.poll_response",
		PriorityClass: 5,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"org.matrix.msc3381.poll.response\"}",
		},
		DefaultEnabled: true,
	},
}

// baseAppendContent ports BASE_APPEND_CONTENT_RULES.
var baseAppendContent = []Rule{
	{
		RuleID:        "global/content/.m.rule.contains_user_name",
		PriorityClass: 4,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"content.body\",\"pattern_type\":\"user_localpart\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\"}",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
		},
		DefaultEnabled: true,
	},
}

// baseAppendPostcontent ports BASE_APPEND_POSTCONTENT_RULES.
var baseAppendPostcontent = []Rule{
	{
		RuleID:        "global/postcontent/.io.element.msc4306.rule.unsubscribed_thread",
		PriorityClass: 6,
		Conditions: []string{
			"{\"kind\":\"io.element.msc4306.thread_subscription\",\"subscribed\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/postcontent/.io.element.msc4306.rule.subscribed_thread",
		PriorityClass: 6,
		Conditions: []string{
			"{\"kind\":\"io.element.msc4306.thread_subscription\",\"subscribed\":true}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
		},
		DefaultEnabled: true,
	},
}

// baseAppendUnderride ports BASE_APPEND_UNDERRIDE_RULES.
var baseAppendUnderride = []Rule{
	{
		RuleID:        "global/underride/.m.rule.call",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.call.invite\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"sound\",\"value\":\"ring\"}",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.m.rule.encrypted_room_one_to_one",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.room.encrypted\"}",
			"{\"kind\":\"room_member_count\",\"is\":\"2\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.m.rule.room_one_to_one",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.room.message\"}",
			"{\"kind\":\"room_member_count\",\"is\":\"2\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc3933.rule.extensible.encrypted_room_one_to_one",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"org.matrix.msc1767.encrypted\"}",
			"{\"kind\":\"room_member_count\",\"is\":\"2\"}",
			"{\"kind\":\"org.matrix.msc3931.room_version_supports\",\"feature\":\"org.matrix.msc3932.extensible_events\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc3933.rule.extensible.message.room_one_to_one",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"org.matrix.msc1767.message\"}",
			"{\"kind\":\"room_member_count\",\"is\":\"2\"}",
			"{\"kind\":\"org.matrix.msc3931.room_version_supports\",\"feature\":\"org.matrix.msc3932.extensible_events\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc3933.rule.extensible.file.room_one_to_one",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"org.matrix.msc1767.file\"}",
			"{\"kind\":\"room_member_count\",\"is\":\"2\"}",
			"{\"kind\":\"org.matrix.msc3931.room_version_supports\",\"feature\":\"org.matrix.msc3932.extensible_events\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc3933.rule.extensible.image.room_one_to_one",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"org.matrix.msc1767.image\"}",
			"{\"kind\":\"room_member_count\",\"is\":\"2\"}",
			"{\"kind\":\"org.matrix.msc3931.room_version_supports\",\"feature\":\"org.matrix.msc3932.extensible_events\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc3933.rule.extensible.video.room_one_to_one",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"org.matrix.msc1767.video\"}",
			"{\"kind\":\"room_member_count\",\"is\":\"2\"}",
			"{\"kind\":\"org.matrix.msc3931.room_version_supports\",\"feature\":\"org.matrix.msc3932.extensible_events\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc3933.rule.extensible.audio.room_one_to_one",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"org.matrix.msc1767.audio\"}",
			"{\"kind\":\"room_member_count\",\"is\":\"2\"}",
			"{\"kind\":\"org.matrix.msc3931.room_version_supports\",\"feature\":\"org.matrix.msc3932.extensible_events\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.m.rule.message",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.room.message\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.m.rule.encrypted",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.room.encrypted\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc1767.rule.extensible.encrypted",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.encrypted\"}",
			"{\"kind\":\"org.matrix.msc3931.room_version_supports\",\"feature\":\"org.matrix.msc3932.extensible_events\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc1767.rule.extensible.message",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.message\"}",
			"{\"kind\":\"org.matrix.msc3931.room_version_supports\",\"feature\":\"org.matrix.msc3932.extensible_events\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc1767.rule.extensible.file",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.file\"}",
			"{\"kind\":\"org.matrix.msc3931.room_version_supports\",\"feature\":\"org.matrix.msc3932.extensible_events\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc1767.rule.extensible.image",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.image\"}",
			"{\"kind\":\"org.matrix.msc3931.room_version_supports\",\"feature\":\"org.matrix.msc3932.extensible_events\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc1767.rule.extensible.video",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.video\"}",
			"{\"kind\":\"org.matrix.msc3931.room_version_supports\",\"feature\":\"org.matrix.msc3932.extensible_events\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc1767.rule.extensible.audio",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"m.audio\"}",
			"{\"kind\":\"org.matrix.msc3931.room_version_supports\",\"feature\":\"org.matrix.msc3932.extensible_events\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.im.vector.jitsi",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"im.vector.modular.widgets\"}",
			"{\"kind\":\"event_match\",\"key\":\"content.type\",\"pattern\":\"jitsi\"}",
			"{\"kind\":\"event_match\",\"key\":\"state_key\",\"pattern\":\"*\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"highlight\",\"value\":false}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc3930.rule.poll_start_one_to_one",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"room_member_count\",\"is\":\"2\"}",
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"org.matrix.msc3381.poll.start\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc3930.rule.poll_start",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"org.matrix.msc3381.poll.start\"}",
		},
		Actions: []string{
			"\"notify\"",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc3930.rule.poll_end_one_to_one",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"room_member_count\",\"is\":\"2\"}",
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"org.matrix.msc3381.poll.end\"}",
		},
		Actions: []string{
			"\"notify\"",
			"{\"set_tweak\":\"sound\",\"value\":\"default\"}",
		},
		DefaultEnabled: true,
	},
	{
		RuleID:        "global/underride/.org.matrix.msc3930.rule.poll_end",
		PriorityClass: 1,
		Conditions: []string{
			"{\"kind\":\"event_match\",\"key\":\"type\",\"pattern\":\"org.matrix.msc3381.poll.end\"}",
		},
		Actions: []string{
			"\"notify\"",
		},
		DefaultEnabled: true,
	},
}
